//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSCommunity.Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedValidationMessages_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedValidationMessages_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KCSCommunity.Application.Resources.SharedValidationMessages_en_US", typeof(SharedValidationMessages_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NotEmptyValidator {
            get {
                return ResourceManager.GetString("NotEmptyValidator", resourceCulture);
            }
        }
        
        internal static string MinimumLengthValidator {
            get {
                return ResourceManager.GetString("MinimumLengthValidator", resourceCulture);
            }
        }
        
        internal static string PasswordUppercaseValidator {
            get {
                return ResourceManager.GetString("PasswordUppercaseValidator", resourceCulture);
            }
        }
        
        internal static string PasswordLowercaseValidator {
            get {
                return ResourceManager.GetString("PasswordLowercaseValidator", resourceCulture);
            }
        }
        
        internal static string PasswordDigitValidator {
            get {
                return ResourceManager.GetString("PasswordDigitValidator", resourceCulture);
            }
        }
        
        internal static string PasswordNonAlphanumericValidator {
            get {
                return ResourceManager.GetString("PasswordNonAlphanumericValidator", resourceCulture);
            }
        }
    }
}
