name: Build, Test, and Deploy Swagger UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
      
      # ✅ 安装 Swagger CLI 工具（只安装）
      - name: Install Swagger CLI
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli
      
      # ✅ 添加 PATH 并生成 swagger.json（必须同一 step）
      - name: Generate swagger.json
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet build ./KCSCommunity.Access/KCSCommunity.Access.csproj --configuration Debug
          swagger tofile \
            --output swagger.json \
            ./KCSCommunity.Access/bin/Debug/net8.0/KCSCommunity.Access.dll \
            v1
      
      # ✅ 生成 Swagger UI 静态页面
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1.3.0
        with:
          output: swagger-ui
          spec-file: swagger.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # ✅ 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
          publish_branch: gh-pages